### ISSUE TITLE
cant navigate to paths on windows

### ISSUE THREAD

**Issue by bioteck** [ctf0/laravel-goto-config#2]
When I do a CTRL+click on a config link, I get this dialog :

<img width="365" alt="vscode_laravel-goto-config_alert_01" src="https://user-images.githubusercontent.com/5863239/107120276-ffb9aa00-688c-11eb-891e-da2c62ace8c5.png">

And then, when I click on "Open", I get this dialog :

<img width="326" alt="vscode_laravel-goto-config_alert_02" src="https://user-images.githubusercontent.com/5863239/107120293-15c76a80-688d-11eb-9d7d-1bc7576e15e3.png">

VSCode version : 1.52.1
Extension version : 0.2.5

**Comment by ctf0** [comment]
- the first dialog is expected as this is how vscode is protecting u from opening unknown types links, so check `dont ask again` and continue like normla.

- the second dialog, i'vent tested on windows, can u show me what value do u get in the hover popup ?

**Comment by bioteck** [comment]
Thanks for your prompt response! Yes, I'm on Windows 10.

The hover works on Laravel v7 and v8:

<img width="330" alt="vscode_laravel-goto-config_alert_03" src="https://user-images.githubusercontent.com/5863239/107121523-3b577280-6893-11eb-8f41-1c9c53fb3eea.png">

But not with Laravel <v7 (v5.8 in this case):

<img width="334" alt="vscode_laravel-goto-config_alert_04" src="https://user-images.githubusercontent.com/5863239/107121534-54f8ba00-6893-11eb-803d-7394f3ecafd4.png">

**Comment by ctf0** [comment]
i cant really remember but was the app structure different from the the current v7+ ?

**Comment by ctf0** [comment]
i think i know the issue, from the rdme
> showing value on hover `laravel/tinker` must be installed

which means unless u install tinker, u r out of luck

**Comment by bioteck** [comment]
Yes, Tinker is installed but the "--execute" option does not exist:

<img width="386" alt="vscode_laravel-goto-config_alert_05" src="https://user-images.githubusercontent.com/5863239/107141978-51654180-692c-11eb-8ffb-f4426cde0aec.png">

But this does not explain why the goto does not work.

**Comment by ctf0** [comment]
is this a multi workspace setup ? atm we only support single workspace per app.

can u also show me what the error u get in the console ?

**Comment by bioteck** [comment]
No, I don't use multi workspace setup.

The console? Do you mean the developer tools? I don't see any error here.

**Comment by ctf0** [comment]
> Do you mean the developer tools

yeap

i think i now know the issue, on windows the path sep is `\` on unix its `/` which we use, thats why u cant navigate correctly to anyplace, i will try to fix that in the next version.

**Comment by ctf0** [comment]
plz try with this version & reply back 

- download the below file
- rename `zip` to `vsix`
- install with vscode

[laravel-goto-config-0.2.5.zip](https://github.com/ctf0/laravel-goto-config/files/5947680/laravel-goto-config-0.2.5.zip)

**Comment by bioteck** [comment]
Sorry, it doesnt work: the link leads to the root of my C: drive:

<img width="290" alt="vscode_laravel-goto-config_alert_06" src="https://user-images.githubusercontent.com/5863239/107334277-cb293680-6ab6-11eb-979e-ceb1060da26f.png">

If it cans help you, I have no problem with the [codingyu.laravel-goto-view](https://github.com/codingyu/laravel-goto-view) extension.

**Comment by ctf0** [comment]
am not sure what to make from the screenshot but anyway `codingyu.laravel-goto-view` is actually using the fixed path separator & unfortunately i cant help any longer as am debugging in the blind.

if u can debug the issue and tell me where to look or even send a PR it would be very helpful.

**Comment by bioteck** [comment]
OK no problem, I will look at this as soon as I have time. Thanks for your support.

**Comment by mr-chetan** [comment]
I find a solution  please check this  https://github.com/ctf0/laravel-goto-config/pull/3

https://github.com/mr-chetan/laravel-goto-config/tree/patch-1


@bioteck @ctf0
