### ISSUE TITLE
Using extension with docker php

### ISSUE THREAD

**Issue by ljubadr** [ctf0/laravel-goto-config#4]
Thank you for this great extension!

I'm currently using `docker-compose` to run laravel and my `.env` is pointing to `mysql` inside of the docker. That's why running `php artisan tinker ...` on host computer throws errors like this one

```
[2022-03-02 16:59:04] local.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known...
```

and my log file is getting filled with same error

Could you add support to run `php` from inside of the docker containers? It would be nice if we could specify the `php` executable either with `"php.validate.executablePath"` or maybe with some new setting that extension provides. For example [Laravel extra Intellisense](https://github.com/amir9480/vscode-laravel-extra-intellisense#laravelextraintellisensephpcommand) extension has `LaravelExtraIntellisense.phpCommand` setting where we can specify `php` executable and I use it like this

```json
"LaravelExtraIntellisense.phpCommand": "docker-compose -f docker-compose.yml exec -T --user=laradock workspace php -r \"{code}\"",
```

this way it will run the `php` from inside of the container and not from host

You also maintain multiple `laravel-goto-*` extensions. Would it be possible to add the same settings to those extensions as well? Maybe they could all share the same setting?

**Comment by ctf0** [comment]
actually thats a very good idea, will surly add it, thank you.

**Comment by ljubadr** [comment]
Thanks a lot! And thanks for the quick reply 👍  I love and use most of your laravel vscode extensions 🥇

**Comment by ljubadr** [comment]
I've looked into Laravel Extra Intellisense extension and [here is how they use the phpCommand  settings](https://github.com/amir9480/vscode-laravel-extra-intellisense/blob/5ff178fad4a19e8a4e88c1836e2dd1cb9e4b334b/src/helpers.ts#L132)

```javascript
/**
 * run simple php code.
 *
 * @param code
 */
static async runPhp(code: string) : Promise<string> {
    code = code.replace(/\"/g, "\\\"");
    if (['linux', 'openbsd', 'sunos', 'darwin'].some(unixPlatforms => os.platform().includes(unixPlatforms))) {
        code = code.replace(/\$/g, "\\$");
        code = code.replace(/\\\\'/g, '\\\\\\\\\'');
        code = code.replace(/\\\\"/g, '\\\\\\\\\"');
    }
    let command = vscode.workspace.getConfiguration("LaravelExtraIntellisense").get<string>('phpCommand') ?? "php -r \"{code}\"";
    command = command.replace("{code}", code);
    let out = new Promise<string>(function (resolve, error) {
        cp.exec(command, function (err, stdout, stderr) {
            if (stdout.length > 0) {
                resolve(stdout);
            } else {
                error(stderr);
            }
        });
    });
    return out;
}
```

**Comment by ctf0** [comment]
plz remove the `.zip` & manually install it then reply back with any findings
[laravel-goto-config-0.2.7.vsix.zip](https://github.com/ctf0/laravel-goto-config/files/8206366/laravel-goto-config-0.2.7.vsix.zip)

the new setting is called `laravelGotoConfig.phpCommand`

**Comment by ljubadr** [comment]
Thanks for the quick update. I'll test this today and I'll let you know how it went

**Comment by ljubadr** [comment]
I just tested it. It's working properly and the error log is not showing anymore. Great job 🥳 

I noticed that `laravelGotoConfig.phpCommand` needs to be added to readme

**Comment by ctf0** [comment]
yeah i will publish the new version, thanks for the good idea
